# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.CharField(max_length=140),
        ),
    ]
