# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20170522_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
